function [H, v, e] = H_tm_hydro(Om, op, kx, ky, beta)
H = [[0, 1j*Om, -1j*op, 0, 0, beta*kx];...
    [-1j*Om, 0, 0, -1j*op, 0, beta*ky];...
    [1j*op, 0, 0, 0, -ky, 0];...
    [0, 1j*op, 0, 0, kx, 0];...
    [0, 0, -ky, kx, 0, 0];...
    [beta*kx, beta*ky, 0, 0, 0, 0]];
[v, e] = eig(H);